### ISSUE TITLE
提高幸福指数的实用功能

### ISSUE THREAD

**Issue by lihuagang03** [quickhack/Effective-IntelliJ-IDEA#1]
玩得就是速度！

- 最特殊的快捷键 Alt + Enter 介绍
- 特殊代码模板：Postfix Completion
- Java 热部署插件 JRebel 安装及使用

https://github.com/judasn/IntelliJ-IDEA-Tutorial

**Comment by oldratlee** [comment]
@EdwardLee03 整理很给力！

**Comment by lihuagang03** [comment]
@oldratlee 工欲善其事，必先利其器 么。哈哈，不是我整理的哦，必须感谢原作者 @judasn

**Comment by judasn** [comment]
也顺路给我点个赞~

**Comment by oldratlee** [comment]
已经加到 READE.md 上了 :) 多谢～  @judasn @EdwardLee03 

PS： 妥妥已 star @judasn 你的repo ，哈哈
